server:
  port: 84

spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.25.128:8848
    sentinel:
      transport:
        dashboard: 192.168.25.128:8858
        port: 8719

service-url:
  nacos-user-service: http://nacos-payment-provider

#Feign对sentinel的支持
feign:
  sentinel:
    enabled: true